name: Build web demo

on:
  push:
    branches: [ ci-web-demo ]

jobs:
  create-nightly-release:
    name: Create nightly release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      date: ${{ steps.current_time_underscores.outputs.formattedTime }}
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current_time_dashes
        with:
          format: YYYY-MM-DD

      - name: Get current time with underscores
        uses: 1466587594/get-current-time@v2
        id: current_time_underscores
        with:
          format: YYYY_MM_DD

  build-desktop-nightlies:
    name: Build desktop nightly for ${{ matrix.os }}
    needs: create-nightly-release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get -y install libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Setup node
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build web
        if: matrix.os == 'ubuntu-latest'
        working-directory: web
        run: |
          npm run bootstrap
          npm run build

      - name: Get web demo
        if: matrix.os == 'ubuntu-latest'
        uses: actions/checkout@v2
        with:
          repository: Herschel/demo
          path: demo
          ref: master
          fetch-depth: 0
          persist-credentials: false # Needed to allow commit via DEMO_TOKEN below

      - name: Update web demo
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd demo

          # Delete the old build.
          rm -f *.js *.wasm *.html

          # Copy the fresh build into this folder.
          cp -f ../web/packages/demo/dist/* .
          touch foo

          # Create git commit. Amend previous commit to avoid daily commit spam.
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git add *
          git commit --amend -am "Nightly build ${{ needs.create-nightly-release.outputs.date }}"
          cd ..

      - name: Push web demo
        if: matrix.os == 'ubuntu-latest'
        uses: ad-m/github-push-action@master
        with:
          repository: Herschel/demo
          github_token: ${{ secrets.DEMO_TOKEN }}
          directory: demo
          force: true
