name: Release Nightly

on:
  # Run nightly
  schedule:
    - cron: "0 0 * * *"

  # Allow for manual dispatch on GitHub
  workflow_dispatch:

jobs:
  create-nightly-release:
    name: Create Nightly Release
    runs-on: ubuntu-latest
    outputs:
      activity_check: ${{ env.GHA_REPO_ALIVE }}
      date: ${{ steps.current_time_underscores.outputs.formattedTime }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Activity check
        run: |
          :
          # Based off https://github.community/t/trigger-workflow-if-there-is-commit-in-last-24-hours/17074/3
          curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/commits | jq -r '[.[]][0]' > $HOME/commit.json
          date="$(jq -r '.commit.committer.date' $HOME/commit.json)"
          timestamp=$(date --utc -d "$date" +%s)
          days=$(( ( $(date --utc +%s) - $timestamp ) / 86400 ))
          author="$(jq -r '.commit.committer.name' $HOME/commit.json)"
          url="$(jq -r '.html_url' $HOME/commit.json)"
          rm -f $HOME/commit.json
          echo "Repository activity: $timestamp $author $url"
          alive=0
          if [ "${{ github.event_name }}" == "repository_dispatch" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "[WARNING] Ignoring activity check: workflow triggered manually."
            alive=1
          elif [[ $days < 1 ]]; then
            echo Repository active
            alive=1
          else
            echo "[WARNING] Repository not updated: event ${{ github.event_name }} not allowed to modify stale repository."
          fi
          if [[ $alive == 1 ]]; then
            echo "GHA_REPO_ALIVE=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Get current time with dashes
        uses: 1466587594/get-current-time@v2
        id: current_time_dashes
        with:
          format: YYYY-MM-DD

      - name: Get current time with underscores
        uses: 1466587594/get-current-time@v2
        id: current_time_underscores
        with:
          format: YYYY_MM_DD

      - name: Create release
        if: env.GHA_REPO_ALIVE == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ steps.current_time_dashes.outputs.formattedTime }}
          release_name: Nightly ${{ steps.current_time_dashes.outputs.formattedTime }}
          prerelease: true

  build:
    name: Build ${{ matrix.platform }}
    needs: create-nightly-release
    if: needs.create-nightly-release.outputs.activity_check == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            package_extension: tar.gz

          - platform: mac
            os: macos-latest
            package_extension: tar.gz
            # Mac does two Rust builds to make a universal binary
            extra_target: aarch64-apple-darwin

          - platform: windows
            os: windows-latest
            package_extension: zip
            # Statically link to CRT on Windows to avoid users needing MSVC libraries.
            RUSTFLAGS: -Ctarget-feature=+crt-static

    runs-on: ${{ matrix.os }}
    env:
      PACKAGE_NAME: ruffle_nightly_${{ needs.create-nightly-release.outputs.date }}_${{ matrix.platform }}.${{ matrix.package_extension }}

    steps:
      - name: Clone Ruffle repo
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.extra_target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: sudo apt install -y libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Set SDK path for macOS aarch64
        if: matrix.platform == 'mac'
        run: |
          cc -v
          xcrun --show-sdk-path
          xcode-select --print-path
          echo "SDKPATH=`xcrun --sdk macosx11.1 --show-sdk-path`" >> $GITHUB_ENV
          echo "CC=`xcrun --sdk macosx11.1 --find clang`" >> $GITHUB_ENV
          echo "CFLAGS=-isysroot `xcrun --sdk macosx11.1 --show-sdk-path`" >> $GITHUB_ENV
          echo "LD=`xcrun --sdk macosx11.1 --find ld`" >> $GITHUB_ENV

      - name: Build macOS aarch64
        if: matrix.platform == 'mac'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package ruffle_desktop --release --target=aarch64-apple-darwin
        env:
          RUSTFLAGS: ${{ matrix.RUSTFLAGS }} -C linker=${{ env.LD }} -C link-args=-libsysroot=${{ env.SDKPATH }}

      - name: Make macOS universal binary
        if: matrix.platform == 'mac'
        run: |
          lipo -create -output ruffle_desktop target/release/ruffle_desktop target/aarch64-apple-darwin/release/ruffle_desktop
          mv -f ruffle_desktop target/release/ruffle_desktop

      - name: Package common
        shell: bash
        run: |
          mkdir package
          cp README.md package/README.md
          cp LICENSE.md package/LICENSE.md

      - name: Package Windows
        if: matrix.platform == 'windows'
        run: |
          cp target/release/ruffle_desktop.exe package/ruffle.exe
          7z a ${{ env.PACKAGE_NAME }} ./package/*

      - name: Package Linux/macOS
        if: matrix.platform != 'windows'
        run: |
          cp target/release/ruffle_desktop package/ruffle
          cd package/
          tar -czvf ../${{ env.PACKAGE_NAME }} *

      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-nightly-release.outputs.upload_url }}
          asset_path: ./${{ env.PACKAGE_NAME }}
          asset_name: ${{ env.PACKAGE_NAME }}
          asset_content_type: ${{ matrix.package_extension == 'tar.gz' && 'application/gzip' || 'application/zip' }}

  build-web:
    name: Build web
    needs: create-nightly-release
    if: needs.create-nightly-release.outputs.activity_check == 'true'
    runs-on: ubuntu-latest
    env:
      PACKAGE_PREFIX: ruffle_nightly_${{ needs.create-nightly-release.outputs.date }}
    steps:
      - name: Clone Ruffle repo
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      # wasm-bindgen-cli version must match wasm-bindgen crate version.
      # Be sure to update in test_web.yml, web/Cargo.toml and web/README.md.
      - name: Install wasm-bindgen
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-bindgen-cli --version 0.2.73

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: binaryen

      # conda is available only with "shell: bash -l {0}".
      # See https://github.com/marketplace/actions/setup-miniconda.
      - name: Install binaryen
        shell: bash -l {0}
        run: conda install -c conda-forge binaryen

      - name: Build web
        env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          MOZILLA_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
          MOZILLA_API_SECRET: ${{ secrets.MOZILLA_API_SECRET }}
          BUILD_ID: ${{ github.run_number }}
        working-directory: web
        shell: bash -l {0}
        run: |
          npm run bootstrap
          npm run build
          npm run docs

      - name: Package selfhosted
        run: |
          cd web/packages/selfhosted/dist/
          zip -r release.zip .

      - name: Upload selfhosted
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-nightly-release.outputs.upload_url }}
          asset_path: ./web/packages/selfhosted/dist/release.zip
          asset_name: ${{ env.PACKAGE_PREFIX }}_selfhosted.zip
          asset_content_type: application/zip

      - name: Upload generic extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-nightly-release.outputs.upload_url }}
          asset_path: ./web/packages/extension/dist/ruffle_extension.zip
          asset_name: ${{ env.PACKAGE_PREFIX }}_extension.zip
          asset_content_type: application/zip

      - name: Upload Firefox extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-nightly-release.outputs.upload_url }}
          asset_path: ./web/packages/extension/dist/firefox.xpi
          asset_name: ${{ env.PACKAGE_PREFIX }}_firefox.xpi
          asset_content_type: application/x-xpinstall

      - name: Clone web demo
        uses: actions/checkout@v2
        with:
          repository: ruffle-rs/demo
          path: demo
          ref: master
          fetch-depth: 0
          persist-credentials: false # Needed to allow commit via RUFFLE_BUILD_TOKEN below

      - name: Update web demo
        run: |
          cd demo/

          # Delete the old build.
          rm -f *.js *.wasm *.html

          # Copy the fresh build into this folder.
          cp -f ../web/packages/demo/dist/* .

          # Create git commit. Amend previous commit to avoid daily commit spam.
          git config user.name "RuffleBuild"
          git config user.email "ruffle@ruffle.rs"
          git add -A
          git commit --amend -m "Nightly build ${{ needs.create-nightly-release.outputs.date }}"

      - name: Push web demo
        uses: ad-m/github-push-action@master
        with:
          repository: ruffle-rs/demo
          github_token: ${{ secrets.RUFFLE_BUILD_TOKEN }}
          directory: demo
          force: true

      - name: Clone JS docs
        uses: actions/checkout@v2
        with:
          repository: ruffle-rs/js-docs
          path: js-docs
          ref: master
          fetch-depth: 0
          persist-credentials: false # Needed to allow commit via RUFFLE_BUILD_TOKEN below

      - name: Update JS docs
        run: |
          cd js-docs/

          # Delete the old docs
          rm -rf master/

          # Copy the fresh docs into this folder.
          cp -r ../web/packages/core/docs master

          # Create git commit. Amend previous commit to avoid daily commit spam.
          git config user.name "RuffleBuild"
          git config user.email "ruffle@ruffle.rs"
          git add -A
          git commit --amend -m "Nightly build ${{ needs.create-nightly-release.outputs.date }}"

      - name: Push JS docs
        uses: ad-m/github-push-action@master
        with:
          repository: ruffle-rs/js-docs
          github_token: ${{ secrets.RUFFLE_BUILD_TOKEN }}
          directory: js-docs
          force: true

  publish-aur-package:
    name: Publish AUR package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current time with dashes
        uses: 1466587594/get-current-time@v2
        id: current_time_dashes
        with:
          format: YYYY-MM-DD

      - name: Get current time with dots
        uses: 1466587594/get-current-time@v2
        id: current_time_dots
        with:
          format: YYYY.MM.DD

      - name: Update PKGBUILD
        run: sed -e "s/@VERSION@/${{ steps.current_time_dots.outputs.formattedTime }}/" -i ./PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.3
        with:
          pkgname: ruffle-nightly-bin
          pkgbuild: ./PKGBUILD
          commit_username: RuffleBuild
          commit_email: ruffle@ruffle.rs
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update to Nightly ${{ steps.current_time_dashes.outputs.formattedTime }}
